### ISSUE TITLE
`go install github.com/dylandreimerink/edb@latest` error

### ISSUE THREAD

**Issue by nevermosby** [dylandreimerink/edb#1]
Hi,

Great to see the missing debug tool for ebpf has finally come~

However, I can't install edb successfully, the error messages are listed below:
```shell
> go install github.com/dylandreimerink/edb@latest
go install: github.com/dylandreimerink/edb@latest (in github.com/dylandreimerink/edb@v0.0.0-20220126224029-c3aec6022385):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```
Could u pls take a look?

BTW, I just built the code manually and got the right binary.

**Comment by dylandreimerink** [comment]
Ah, I didn't know that `replace` directives can mess with the `go install` command, good to know. I guess I will update the readme to advice people to clone and compile oldschool style until `edb` is stable enought to warrent the release of pre-built executables.

**Comment by nevermosby** [comment]
Gotcha,I will close the issue for now
