### ISSUE TITLE
error while installing the package

### ISSUE THREAD

**Issue by guyarb** [dylandreimerink/edb#3]
Wanted to test `edb` and tried to install it using `go install ...` command line (as appears in the readme) but unfortunately I got the error below.
![image](https://user-images.githubusercontent.com/17148247/152099957-1c4bc527-e30a-4185-aa2a-18cebb1240d5.png)

**Comment by guyarb** [comment]
Only now I noticed the `note` in the readme 😞 
Maybe it is worth to remove that option from the README until the issue is fixed

**Comment by dylandreimerink** [comment]
Yea, I am sort of hoping that SLL2 support is merged into the main repo within a reasonable amount of time https://github.com/google/gopacket/pull/933 so I can remove the redirect directive. If will give it a week or so, if nothing happens(the project seems abandoned by the lack of issue and PR responses in the last months), I might just permanently fork it with a different module path so I can just straight up include it without the redirect directive.

Also the limitation what `go install` only works with redirect directives if you download the sources manually feels really arbitrary to me. It is likely some sort of security measure, but I don't fully understand.

In my eyes this is also fixes as soon as the first actual release happens, but I don't feel like we support enough eBPF programs yet to call it an actually useful release yet.

I will leave this issue open until installation with `go install` is fixed one way or another.

**Comment by dylandreimerink** [comment]
I am happy to announce that I have created the first release of `edb`. You can find installation instructions [here](https://github.com/dylandreimerink/edb#binary-release) and the v0.1.0 release [here](https://github.com/dylandreimerink/edb/releases/tag/v0.1.0).
